### ISSUE TITLE
notification stay as permanent not working

### ISSUE THREAD

**Issue by RohanRon** [prajjwaldimri/Friend-App#55]
The BeFriend app shows a notification on Windows phones' Action Centre. However, currently it is possible to clear the Action Centre and that notification disappears. 

Not sure if permanent notifications hasn't been implemented or not. I'm also contact a friend to see if he would like to join in the development of app.

**Comment by prajjwaldimri** [comment]
@RohanRon There is no way permanent toast notification can be added to the app(no windows api), so I created a workaround in which the app runs a background service every 5 hours and checks if currently there is any toast notification of the app in the 'Action Center'. If it didn't find one it adds a toast notification to the action center silently. You can check this feature by enabling the toggle button for 'permanent toast notification' in 'settings page' of the app
